/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package quick.start

import ihm.console.TestConsole

class App {
}

fun main(args: Array<String>) {
    println("Jeu lancé")

    val testConsole = TestConsole();

    testConsole.start();
}
